default_language_version:
  python: python3.8
default_stages: [commit]
files: ^openedx/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    - id: isort

# flake8
- repo: https://github.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      # See https://github.com/DmytroLitvinov/awesome-flake8-extensions for extensions
      args: ['--config=setup.cfg']
      additional_dependencies: [
        "flake8-print",
        "flake8-simplify",
        "flake8-isort",
      ]
