# Generated by Django 2.2.25 on 2022-06-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFavoriteClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genplus.Teacher')),
            ],
            options={
                'unique_together': {('rm_class', 'teacher')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='favourite_classes',
            field=models.ManyToManyField(through='genplus.TeacherFavoriteClass', to='genplus.Class'),
        ),
    ]
