# Generated by Django 2.2.25 on 2022-10-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0002_auto_20221003_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstudents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='genplus.Student'),
        ),
    ]
