# Generated by Django 2.2.25 on 2022-10-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0003_auto_20221004_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
