# Generated by Django 2.2.25 on 2022-11-17 13:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genplus', '0005_auto_20221104_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('email_reference', models.BigIntegerField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('M', 'M'), ('i', 'i'), ('s', 's'), ('s', 's'), ('i', 'i'), ('n', 'n'), ('g', 'g'), (' ', ' '), ('C', 'C'), ('l', 'l'), ('a', 'a'), ('s', 's'), ('s', 's')], max_length=128)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
