# Generated by Django 2.2.25 on 2022-11-27 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_teach', '0010_auto_20221127_0948'),
        ('genplus_learning', '0004_auto_20221127_0948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genplus', '0008_auto_20221126_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Affiliate', 'Affiliate'), ('Employee', 'Employee'), ('TeachingStaff', 'TeachingStaff'), ('NonTeachingStaff', 'NonTeachingStaff')], max_length=32, null=True)),
                ('year_of_entry', models.CharField(blank=True, max_length=32, null=True)),
                ('registration_group', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='gen_plus_teachers')),
                ('onboarded', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='genuser',
            name='school',
        ),
        migrations.RemoveField(
            model_name='genuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='character',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gen_user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gen_user',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='gen_class',
        ),
        migrations.RemoveField(
            model_name='teacherclass',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalpost',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClassStudents',
        ),
        migrations.DeleteModel(
            name='GenUser',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherClass',
        ),
        migrations.AddField(
            model_name='genuserprofile',
            name='active_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Class'),
        ),
        migrations.AddField(
            model_name='genuserprofile',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.Character'),
        ),
        migrations.AddField(
            model_name='genuserprofile',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='gen_users', to='genplus.Class'),
        ),
        migrations.AddField(
            model_name='genuserprofile',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.School'),
        ),
        migrations.AddField(
            model_name='genuserprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gen_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('genplus.genuserprofile',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('genplus.genuserprofile',),
        ),
    ]
