# Generated by Django 2.2.25 on 2023-09-17 22:16

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_auth', '0004_auto_20200919_0955'),
        ('genplus', '0017_school_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('saml_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='third_party_auth.SAMLProviderConfig')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='school',
            name='local_authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='genplus.LocalAuthority'),
        ),
    ]
