# Generated by Django 2.2.25 on 2022-06-23 14:23

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0002_unit_squashed_0004_remove_unit_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_key', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('is_locked', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='genplus_learning.Unit')),
            ],
            options={
                'unique_together': {('unit', 'usage_key')},
            },
        ),
    ]
