# Generated by Django 2.2.25 on 2022-11-27 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('genplus_learning', '0003_auto_20221118_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programunitenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='programunitenrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='programunitenrollment',
            name='course_enrollment',
        ),
        migrations.RemoveField(
            model_name='programunitenrollment',
            name='program_enrollment',
        ),
        migrations.AlterField(
            model_name='classlesson',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='classlesson',
            name='usage_key',
            field=opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='classunit',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalprogramenrollment',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalProgramUnitEnrollment',
        ),
        migrations.DeleteModel(
            name='ProgramUnitEnrollment',
        ),
    ]
